In [3]:
pip install pandas numpy

Defaulting to user installation because normal site-packages is not writeable
Collecting pandas
  Downloading pandas-2.3.3-cp313-cp313-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy in c:\users\junqi.wu\appdata\roaming\python\python313\site-packages (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\junqi.wu\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\junqi.wu\appdata\roaming\python\python313\site-packages (from pandas) (2025.2)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\junqi.wu\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.3.3-cp313-cp313-win_amd64.whl (11.0 MB)
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   --------------------- ------------------ 6.0/11.0 MB 31.4 MB/s eta 0:00:01
   ---------------------------------------  10.7/11.0 MB 27.9 MB/s eta 0:00:01
   ---------------------------------------- 11.0/11.0 MB 26.3 MB/s  0:00:00
Downloading tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Installing collected packages: tzdata, pandas

   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   ---------------------------------------- 2/2 [pandas]

Successfully installed pandas-2.3.3 tzdata-2025.2
Note: you may need to restart the kernel to use updated packages.

In [127]:
import pandas as pd
import numpy as np

# Data Structures

## Series: creating by pd.Series()

In [165]:
ls = [1,2,3, "hello", np.nan, 1.5] # elements can be of different types
pds = pd.Series(ls)
print(pds)

0        1
1        2
2        3
3    hello
4      NaN
5      1.5
dtype: object

## Data Frame

### Creating by pd.DataFrame()

In [223]:
dic = {
    "feature_1": [1,2,3],
    "feature_2": [1,0,1],
    "feature_3": ["F", "M","F"]
}

df = pd.DataFrame(dic)
print(df)

   feature_1  feature_2 feature_3
0          1          1         F
1          2          0         M
2          3          1         F

### Creating by pd.read_csv()

In [224]:
df = pd.read_csv(
    "airlines_flights_data.csv",
    header = 0
    # index_col = 'index' # specify column "index" as index
)

In [225]:
df = df.drop(columns = ["index"])
df.head()

,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955

# EDA & Data Cleaning

## Data Description

In [226]:
df.info() # checking data types and non-null values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300153 entries, 0 to 300152
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   airline           300153 non-null  object
 1   flight            300153 non-null  object
 2   source_city       300153 non-null  object
 3   departure_time    300153 non-null  object
 4   stops             300153 non-null  object
 5   arrival_time      300153 non-null  object
 6   destination_city  300153 non-null  object
 7   class             300153 non-null  object
 8   duration          300153 non-null  float64
 9   days_left         300153 non-null  int64
 10  price             300153 non-null  int64
dtypes: float64(1), int64(2), object(8)
memory usage: 25.2+ MB

In [227]:
# check statistical summary for numerical features
df.describe()

            duration      days_left          price
count  300153.000000  300153.000000  300153.000000
mean       12.221021      26.004751   20889.660523
std         7.191997      13.561004   22697.767366
min         0.830000       1.000000    1105.000000
25%         6.830000      15.000000    4783.000000
50%        11.250000      26.000000    7425.000000
75%        16.170000      38.000000   42521.000000
max        49.830000      49.000000  123071.000000

In [228]:
# Data Slicing

# loc
df.loc[0] # first row
df.loc[0:2, "airline"] # first 3 rows and column "airline"
df.loc[0:2, ["airline", "flight", "source_city"]] # first 3 rows and columns "airline", "flight", "source_city"
df.loc[df["airline"] == "AirAsia", :] # filter rows where source_city is "AirAsia"

,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
18,AirAsia,I5-747,Delhi,Evening,one,Early_Morning,Mumbai,Economy,12.25,1,5949
19,AirAsia,I5-747,Delhi,Evening,one,Morning,Mumbai,Economy,16.33,1,5949
27,AirAsia,I5-744,Delhi,Morning,one,Afternoon,Mumbai,Economy,5.83,1,8869
48,AirAsia,I5-784,Delhi,Evening,one,Early_Morning,Mumbai,Economy,15.17,1,12539
...,...,...,...,...,...,...,...,...,...,...,...
206538,AirAsia,I5-1229,Chennai,Night,one,Morning,Hyderabad,Economy,9.25,48,1550
206539,AirAsia,I5-2462,Chennai,Night,one,Morning,Hyderabad,Economy,10.17,48,1550
206591,AirAsia,I5-517,Chennai,Morning,zero,Morning,Hyderabad,Economy,1.17,49,1105
206616,AirAsia,I5-1229,Chennai,Night,one,Morning,Hyderabad,Economy,9.25,49,1550
206617,AirAsia,I5-2462,Chennai,Night,one,Morning,Hyderabad,Economy,10.17,49,1550

In [229]:
# iloc
df.iloc[0,0] # first row and first column

'SpiceJet'

In [230]:
# iloc
df.iloc[0,0] # first row and first column
df.iloc[0:2, 0:2] # first 2 rows and first 2 columns
df.iloc[:,-1] # last column

0          5953
1          5953
2          5956
3          5955
4          5955
          ...
300148    69265
300149    77105
300150    79099
300151    81585
300152    81585
Name: price, Length: 300153, dtype: int64

In [231]:
df.shape

# rows
df.shape[0]
# columns
df.shape[1]

11

## Column Description

In [232]:
df["airline"].dtypes # check datatypes

dtype('O')

In [233]:
df["airline"].unique() # check unique values

array(['SpiceJet', 'AirAsia', 'Vistara', 'GO_FIRST', 'Indigo',
       'Air_India'], dtype=object)

In [234]:
df["airline"].value_counts() # check value counts

airline
Vistara      127859
Air_India     80892
Indigo        43120
GO_FIRST      23173
AirAsia       16098
SpiceJet       9011
Name: count, dtype: int64

In [235]:
df["airline"].tolist() # convert to list

['SpiceJet',
 'SpiceJet',
 'AirAsia',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'GO_FIRST',
 'GO_FIRST',
 'GO_FIRST',
 'GO_FIRST',
 'Indigo',
 'Indigo',
 'Indigo',
 'Indigo',
 'Air_India',
 'Air_India',
 'AirAsia',
 'AirAsia',
 'GO_FIRST',
 'GO_FIRST',
 'GO_FIRST',
 'Air_India',
 'Indigo',
 'Vistara',
 'Indigo',
 'AirAsia',
 'SpiceJet',
 'Indigo',
 'GO_FIRST',
 'Indigo',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Air_India',
 'SpiceJet',
 'SpiceJet',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'SpiceJet',
 'Vistara',
 'Vistara',
 'AirAsia',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'Indigo',
 'Indigo',
 'Indigo',
 'Indigo',
 'Indigo',
 'Vistara',
 'Air_India',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Indigo',
 'GO_FIRST',
 'Vistara',
 'Vistara',
 'Air_India',
 'GO_FIRST',
 'Vistara',
 'Air_India',
 'Air_India',
 'Vistara',
 'Vistara',
 'Vistara',
 'Indigo',
 'SpiceJet',
 'Indigo',
 'Air_India',
 'Vistara',
 'Vistara',
 'Vistara',
 'Air_India',
 'Air_India',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Air_India',
 'Vistara',
 'Air_India',
 'Vistara',
 'Vistara',
 'GO_FIRST',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Air_India',
 'Air_India',
 'Vistara',
 'Air_India',
 'Vistara',
 'GO_FIRST',
 'Air_India',
 'Air_India',
 'Air_India',
 'Vistara',
 'Air_India',
 'SpiceJet',
 'SpiceJet',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'GO_FIRST',
 'GO_FIRST',
 'GO_FIRST',
 'GO_FIRST',
 'GO_FIRST',
 'GO_FIRST',
 'Indigo',
 'Indigo',
 'Indigo',
 'Indigo',
 'Indigo',
 'Indigo',
 'SpiceJet',
 'Indigo',
 'Indigo',
 'AirAsia',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'AirAsia',
 'AirAsia',
 'GO_FIRST',
 'GO_FIRST',
 'Air_India',
 'Air_India',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'AirAsia',
 'Indigo',
 'Indigo',
 'SpiceJet',
 'SpiceJet',
 'Air_India',
 'Air_India',
 'Air_India',
 'Vistara',
 'Air_India',
 'Indigo',
 'Air_India',
 'Vistara',
 'Indigo',
 'Indigo',
 'Indigo',
 'Air_India',
 'Indigo',
 'Indigo',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Indigo',
 'Indigo',
 'Air_India',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Air_India',
 'Indigo',
 'Air_India',
 'Vistara',
 'Air_India',
 'SpiceJet',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'GO_FIRST',
 'GO_FIRST',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Air_India',
 'GO_FIRST',
 'Vistara',
 'Vistara',
 'Air_India',
 'GO_FIRST',
 'GO_FIRST',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'GO_FIRST',
 'Air_India',
 'Indigo',
 'Air_India',
 'Indigo',
 'SpiceJet',
 'Indigo',
 'Air_India',
 'Vistara',
 'Vistara',
 'GO_FIRST',
 'Vistara',
 'Vistara',
 'GO_FIRST',
 'Air_India',
 'Air_India',
 'Vistara',
 'Vistara',
 'Vistara',
 'Air_India',
 'Air_India',
 'Air_India',
 'GO_FIRST',
 'GO_FIRST',
 'Vistara',
 'Air_India',
 'Vistara',
 'Vistara',
 'Air_India',
 'SpiceJet',
 'SpiceJet',
 'SpiceJet',
 'Vistara',
 'Vistara',
 'Vistara',
 'GO_FIRST',
 'GO_FIRST',
 'GO_FIRST',
 'GO_FIRST',
 'Indigo',
 'Indigo',
 'Indigo',
 'Indigo',
 'AirAsia',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'GO_FIRST',
 'GO_FIRST',
 'Air_India',
 'Vistara',
 'SpiceJet',
 'SpiceJet',
 'Vistara',
 'GO_FIRST',
 'GO_FIRST',
 'Vistara',
 'Air_India',
 'GO_FIRST',
 'Indigo',
 'Indigo',
 'Indigo',
 'Indigo',
 'Indigo',
 'Indigo',
 'Vistara',
 'Vistara',
 'AirAsia',
 'Air_India',
 'Indigo',
 'Vistara',
 'SpiceJet',
 'Air_India',
 'GO_FIRST',
 'Indigo',
 'Vistara',
 'Vistara',
 'Vistara',
 'Indigo',
 'Indigo',
 'Air_India',
 'Vistara',
 'Vistara',
 'SpiceJet',
 'Indigo',
 'Indigo',
 'Air_India',
 'Indigo',
 'SpiceJet',
 'GO_FIRST',
 'GO_FIRST',
 'Air_India',
 'Air_India',
 'Air_India',
 'GO_FIRST',
 'Vistara',
 'Air_India',
 'Vistara',
 'Air_India',
 'Vistara',
 'Indigo',
 'Indigo',
 'AirAsia',
 'Vistara',
 'GO_FIRST',
 'GO_FIRST',
 'Air_India',
 'Vistara',
 'SpiceJet',
 'Indigo',
 'Air_India',
 'Vistara',
 'Vistara',
 'Vistara',
 'Indigo',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'GO_FIRST',
 'Air_India',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Indigo',
 'Vistara',
 'Vistara',
 'Vistara',
 'Air_India',
 'Indigo',
 'Indigo',
 'Vistara',
 'Vistara',
 'Air_India',
 'Indigo',
 'Indigo',
 'Indigo',
 'Air_India',
 'Air_India',
 'Air_India',
 'Vistara',
 'Vistara',
 'GO_FIRST',
 'Vistara',
 'GO_FIRST',
 'Vistara',
 'Vistara',
 'GO_FIRST',
 'Air_India',
 'Vistara',
 'Vistara',
 'Vistara',
 'Air_India',
 'Vistara',
 'Vistara',
 'Air_India',
 'Air_India',
 'Air_India',
 'Vistara',
 'Vistara',
 'GO_FIRST',
 'Air_India',
 'Vistara',
 'Air_India',
 'Air_India',
 'GO_FIRST',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'SpiceJet',
 'SpiceJet',
 'SpiceJet',
 'SpiceJet',
 'SpiceJet',
 'SpiceJet',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'GO_FIRST',
 'GO_FIRST',
 'GO_FIRST',
 'GO_FIRST',
 'GO_FIRST',
 'GO_FIRST',
 'Indigo',
 'Indigo',
 'Indigo',
 'Indigo',
 'SpiceJet',
 'Indigo',
 'Indigo',
 'Indigo',
 'Indigo',
 'Indigo',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'AirAsia',
 'GO_FIRST',
 'GO_FIRST',
 'GO_FIRST',
 'GO_FIRST',
 'GO_FIRST',
 'GO_FIRST',
 'GO_FIRST',
 'Air_India',
 'SpiceJet',
 'Indigo',
 'Indigo',
 'Indigo',
 'SpiceJet',
 'SpiceJet',
 'AirAsia',
 'Indigo',
 'SpiceJet',
 'Vistara',
 'Indigo',
 'GO_FIRST',
 'Indigo',
 'Indigo',
 'Indigo',
 'Indigo',
 'Air_India',
 'Vistara',
 'Vistara',
 'Air_India',
 'Air_India',
 'GO_FIRST',
 'Indigo',
 'Air_India',
 'Air_India',
 'GO_FIRST',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Air_India',
 'Indigo',
 'Air_India',
 'Air_India',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Air_India',
 'Indigo',
 'Indigo',
 'GO_FIRST',
 'GO_FIRST',
 'Air_India',
 'Vistara',
 'Vistara',
 'Vistara',
 'GO_FIRST',
 'GO_FIRST',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'SpiceJet',
 'Air_India',
 'Indigo',
 'Air_India',
 'Indigo',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'GO_FIRST',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'SpiceJet',
 'Vistara',
 'Vistara',
 'Air_India',
 'Air_India',
 'Vistara',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'Vistara',
 'Vistara',
 'GO_FIRST',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'SpiceJet',
 'SpiceJet',
 'SpiceJet',
 'SpiceJet',
 'SpiceJet',
 'SpiceJet',
 'SpiceJet',
 'SpiceJet',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'GO_FIRST',
 'GO_FIRST',
 'GO_FIRST',
 'GO_FIRST',
 'GO_FIRST',
 'GO_FIRST',
 'Indigo',
 'Indigo',
 'Indigo',
 'Indigo',
 'Indigo',
 'Indigo',
 'Indigo',
 'Indigo',
 'Indigo',
 'Indigo',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'AirAsia',
 'AirAsia',
 'GO_FIRST',
 'GO_FIRST',
 'GO_FIRST',
 'GO_FIRST',
 'GO_FIRST',
 'GO_FIRST',
 'GO_FIRST',
 'GO_FIRST',
 'Air_India',
 'SpiceJet',
 'SpiceJet',
 'SpiceJet',
 'SpiceJet',
 'AirAsia',
 'SpiceJet',
 'Indigo',
 'Indigo',
 'GO_FIRST',
 'Indigo',
 'Indigo',
 'Indigo',
 'Indigo',
 'Air_India',
 'Air_India',
 'Indigo',
 'Indigo',
 'Vistara',
 'Vistara',
 'Air_India',
 'GO_FIRST',
 'GO_FIRST',
 'Air_India',
 'Air_India',
 'Air_India',
 'Indigo',
 'Indigo',
 'GO_FIRST',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Air_India',
 'Vistara',
 'Vistara',
 'Vistara',
 'Indigo',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'SpiceJet',
 'Air_India',
 'Vistara',
 'GO_FIRST',
 'GO_FIRST',
 'Air_India',
 'Air_India',
 'GO_FIRST',
 'GO_FIRST',
 'Air_India',
 'GO_FIRST',
 'Air_India',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Air_India',
 'GO_FIRST',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Air_India',
 'Air_India',
 'Air_India',
 'AirAsia',
 'Air_India',
 'Vistara',
 'Air_India',
 'Indigo',
 'Vistara',
 'Vistara',
 'Air_India',
 'Air_India',
 'Vistara',
 'Air_India',
 'Air_India',
 'Air_India',
 'Vistara',
 'Vistara',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'Indigo',
 'Air_India',
 'Air_India',
 'Vistara',
 'Vistara',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'SpiceJet',
 'SpiceJet',
 'SpiceJet',
 'SpiceJet',
 'SpiceJet',
 'SpiceJet',
 'SpiceJet',
 'SpiceJet',
 'AirAsia',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'GO_FIRST',
 'GO_FIRST',
 'GO_FIRST',
 'GO_FIRST',
 'GO_FIRST',
 'GO_FIRST',
 'Indigo',
 'Indigo',
 'Indigo',
 'Indigo',
 'Indigo',
 'Indigo',
 'Indigo',
 'Indigo',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'AirAsia',
 'AirAsia',
 'AirAsia',
 'GO_FIRST',
 'GO_FIRST',
 'GO_FIRST',
 'GO_FIRST',
 'GO_FIRST',
 'GO_FIRST',
 'GO_FIRST',
 'GO_FIRST',
 'GO_FIRST',
 'GO_FIRST',
 'GO_FIRST',
 'Air_India',
 'Air_India',
 'Indigo',
 'SpiceJet',
 'SpiceJet',
 'Indigo',
 'SpiceJet',
 'GO_FIRST',
 'Indigo',
 'Indigo',
 'Indigo',
 'Indigo',
 'Indigo',
 'Indigo',
 'Indigo',
 'Vistara',
 'Vistara',
 'GO_FIRST',
 'AirAsia',
 'Indigo',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Air_India',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Indigo',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'Indigo',
 'Air_India',
 'GO_FIRST',
 'GO_FIRST',
 'SpiceJet',
 'GO_FIRST',
 'Air_India',
 'GO_FIRST',
 'Air_India',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Indigo',
 'Air_India',
 'Air_India',
 'Air_India',
 'Vistara',
 'GO_FIRST',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'SpiceJet',
 'Air_India',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Indigo',
 'Vistara',
 'Air_India',
 'Air_India',
 'Air_India',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Air_India',
 'Indigo',
 'SpiceJet',
 'Air_India',
 'Vistara',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'Vistara',
 'Air_India',
 'Air_India',
 'Indigo',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'Vistara',
 'SpiceJet',
 'SpiceJet',
 'SpiceJet',
 'SpiceJet',
 'SpiceJet',
 'SpiceJet',
 'SpiceJet',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'GO_FIRST',
 'GO_FIRST',
 'GO_FIRST',
 'GO_FIRST',
 'GO_FIRST',
 'Indigo',
 'Indigo',
 'Indigo',
 'Indigo',
 'Indigo',
 'Indigo',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'Air_India',
 'GO_FIRST',
 'GO_FIRST',
 'GO_FIRST',
 'GO_FIRST',
 'GO_FIRST',
 'GO_FIRST',
 'GO_FIRST',
 'GO_FIRST',
 'GO_FIRST',
 'GO_FIRST',
 'Air_India',
 'Air_India',
 'SpiceJet',
 'Indigo',
 'Indigo',
 'SpiceJet',
 'SpiceJet',
 'Indigo',
 'Indigo',
 'AirAsia',
 'GO_FIRST',
 'GO_FIRST',
 'Indigo',
 'Indigo',
 'Indigo',
 'Indigo',
 'Indigo',
 'Indigo',
 'Air_India',
 'Air_India',
 'Vistara',
 'Vistara',
 'Vistara',
 'GO_FIRST',
 'AirAsia',
 'Air_India',
 'Air_India',
 'Air_India',
 'Indigo',
 'Air_India',
 'Indigo',
 ...]

In [236]:
df["airline"].isna().sum() # check missing values

np.int64(0)

### Row Description

In [237]:
df.index

RangeIndex(start=0, stop=300153, step=1)

In [238]:
df.index.tolist()

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318,
 319,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 331,
 332,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 348,
 349,
 350,
 351,
 352,
 353,
 354,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 402,
 403,
 404,
 405,
 406,
 407,
 408,
 409,
 410,
 411,
 412,
 413,
 414,
 415,
 416,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 429,
 430,
 431,
 432,
 433,
 434,
 435,
 436,
 437,
 438,
 439,
 440,
 441,
 442,
 443,
 444,
 445,
 446,
 447,
 448,
 449,
 450,
 451,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 459,
 460,
 461,
 462,
 463,
 464,
 465,
 466,
 467,
 468,
 469,
 470,
 471,
 472,
 473,
 474,
 475,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 486,
 487,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 502,
 503,
 504,
 505,
 506,
 507,
 508,
 509,
 510,
 511,
 512,
 513,
 514,
 515,
 516,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 525,
 526,
 527,
 528,
 529,
 530,
 531,
 532,
 533,
 534,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 543,
 544,
 545,
 546,
 547,
 548,
 549,
 550,
 551,
 552,
 553,
 554,
 555,
 556,
 557,
 558,
 559,
 560,
 561,
 562,
 563,
 564,
 565,
 566,
 567,
 568,
 569,
 570,
 571,
 572,
 573,
 574,
 575,
 576,
 577,
 578,
 579,
 580,
 581,
 582,
 583,
 584,
 585,
 586,
 587,
 588,
 589,
 590,
 591,
 592,
 593,
 594,
 595,
 596,
 597,
 598,
 599,
 600,
 601,
 602,
 603,
 604,
 605,
 606,
 607,
 608,
 609,
 610,
 611,
 612,
 613,
 614,
 615,
 616,
 617,
 618,
 619,
 620,
 621,
 622,
 623,
 624,
 625,
 626,
 627,
 628,
 629,
 630,
 631,
 632,
 633,
 634,
 635,
 636,
 637,
 638,
 639,
 640,
 641,
 642,
 643,
 644,
 645,
 646,
 647,
 648,
 649,
 650,
 651,
 652,
 653,
 654,
 655,
 656,
 657,
 658,
 659,
 660,
 661,
 662,
 663,
 664,
 665,
 666,
 667,
 668,
 669,
 670,
 671,
 672,
 673,
 674,
 675,
 676,
 677,
 678,
 679,
 680,
 681,
 682,
 683,
 684,
 685,
 686,
 687,
 688,
 689,
 690,
 691,
 692,
 693,
 694,
 695,
 696,
 697,
 698,
 699,
 700,
 701,
 702,
 703,
 704,
 705,
 706,
 707,
 708,
 709,
 710,
 711,
 712,
 713,
 714,
 715,
 716,
 717,
 718,
 719,
 720,
 721,
 722,
 723,
 724,
 725,
 726,
 727,
 728,
 729,
 730,
 731,
 732,
 733,
 734,
 735,
 736,
 737,
 738,
 739,
 740,
 741,
 742,
 743,
 744,
 745,
 746,
 747,
 748,
 749,
 750,
 751,
 752,
 753,
 754,
 755,
 756,
 757,
 758,
 759,
 760,
 761,
 762,
 763,
 764,
 765,
 766,
 767,
 768,
 769,
 770,
 771,
 772,
 773,
 774,
 775,
 776,
 777,
 778,
 779,
 780,
 781,
 782,
 783,
 784,
 785,
 786,
 787,
 788,
 789,
 790,
 791,
 792,
 793,
 794,
 795,
 796,
 797,
 798,
 799,
 800,
 801,
 802,
 803,
 804,
 805,
 806,
 807,
 808,
 809,
 810,
 811,
 812,
 813,
 814,
 815,
 816,
 817,
 818,
 819,
 820,
 821,
 822,
 823,
 824,
 825,
 826,
 827,
 828,
 829,
 830,
 831,
 832,
 833,
 834,
 835,
 836,
 837,
 838,
 839,
 840,
 841,
 842,
 843,
 844,
 845,
 846,
 847,
 848,
 849,
 850,
 851,
 852,
 853,
 854,
 855,
 856,
 857,
 858,
 859,
 860,
 861,
 862,
 863,
 864,
 865,
 866,
 867,
 868,
 869,
 870,
 871,
 872,
 873,
 874,
 875,
 876,
 877,
 878,
 879,
 880,
 881,
 882,
 883,
 884,
 885,
 886,
 887,
 888,
 889,
 890,
 891,
 892,
 893,
 894,
 895,
 896,
 897,
 898,
 899,
 900,
 901,
 902,
 903,
 904,
 905,
 906,
 907,
 908,
 909,
 910,
 911,
 912,
 913,
 914,
 915,
 916,
 917,
 918,
 919,
 920,
 921,
 922,
 923,
 924,
 925,
 926,
 927,
 928,
 929,
 930,
 931,
 932,
 933,
 934,
 935,
 936,
 937,
 938,
 939,
 940,
 941,
 942,
 943,
 944,
 945,
 946,
 947,
 948,
 949,
 950,
 951,
 952,
 953,
 954,
 955,
 956,
 957,
 958,
 959,
 960,
 961,
 962,
 963,
 964,
 965,
 966,
 967,
 968,
 969,
 970,
 971,
 972,
 973,
 974,
 975,
 976,
 977,
 978,
 979,
 980,
 981,
 982,
 983,
 984,
 985,
 986,
 987,
 988,
 989,
 990,
 991,
 992,
 993,
 994,
 995,
 996,
 997,
 998,
 999,
 ...]

### Missing Values

In [239]:
df.isna().sum() # check missing values

airline             0
flight              0
source_city         0
departure_time      0
stops               0
arrival_time        0
destination_city    0
class               0
duration            0
days_left           0
price               0
dtype: int64

In [240]:
# drop missing values
df = df.dropna() # as long as there is one missing value, the row will be dropped
df = df.dropna(axis = 1) # drop columns with missing values


df = df.dropna(subset = ["airline"]) # drop rows where "airline" is missing
df = df.dropna(subset = ["airline", "flight"]) # drop rows where "airline" or "flight" is missing

In [241]:
# filling missing values
df = df.fillna(0) # fill missing values with 0
df = df.fillna(method = "ffill") # fill missing values with the previous value
df = df.fillna(method = "bfill") # fill missing values with the next value

C:\Users\junqi.wu\AppData\Local\Temp\ipykernel_4580\3844162867.py:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df = df.fillna(method = "ffill") # fill missing values with the previous value
C:\Users\junqi.wu\AppData\Local\Temp\ipykernel_4580\3844162867.py:4: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df = df.fillna(method = "bfill") # fill missing values with the next value

In [242]:
# replace missing values with a specific value
df = df.replace(np.nan, 0) # replace missing values with 0
df["airline"] = df["airline"].replace("AirAsia", "Air Asia")

### Duplicates

In [243]:
# check dulicates
df.duplicated()
df.duplicated(subset = ['airline', 'flight'])

0         False
1         False
2         False
3         False
4         False
          ...
300148     True
300149     True
300150     True
300151     True
300152     True
Length: 300153, dtype: bool

In [244]:
# drop duplicates
df = df.drop_duplicates(subset = ['airline', 'flight'], keep = 'first')
# keep = 'first'
# keep = 'last'
# keep = False -> drop all duplicates

### Data Type Conversion

In [245]:
## int/float/str does not require ''
df['price'] = df['price'].astype(float)
df['price']

0          5953.0
1          5953.0
2          5956.0
3          5955.0
4          5955.0
           ...
206278     1105.0
206279     1105.0
206345     7268.0
206358     1105.0
211488    44025.0
Name: price, Length: 1561, dtype: float64

In [246]:
## 'category' needs ''
df['airline'] =  df['airline'].astype('category')

In [247]:
## convert to numeric, if cannot then 'NaN'
df['price'] = pd.to_numeric(df['price'], errors = 'coerce')
df['price']

0          5953.0
1          5953.0
2          5956.0
3          5955.0
4          5955.0
           ...
206278     1105.0
206279     1105.0
206345     7268.0
206358     1105.0
211488    44025.0
Name: price, Length: 1561, dtype: float64

### Outliers Detection

In [248]:
df.boxplot(column = 'price')

In [249]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1561 entries, 0 to 211488
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   airline           1561 non-null   category
 1   flight            1561 non-null   object
 2   source_city       1561 non-null   object
 3   departure_time    1561 non-null   object
 4   stops             1561 non-null   object
 5   arrival_time      1561 non-null   object
 6   destination_city  1561 non-null   object
 7   class             1561 non-null   object
 8   duration          1561 non-null   float64
 9   days_left         1561 non-null   int64
 10  price             1561 non-null   float64
dtypes: category(1), float64(2), int64(1), object(7)
memory usage: 135.9+ KB

In [ ]:
### clip
df['price'] = df['price'].clip(0, 40000)
# df['col'].clip(lower_value, upper_value) if lower than lower_value, then lower_value; if larger than upper_value, then upper_value

0          5953.0
1          5953.0
2          5956.0
3          5955.0
4          5955.0
           ...
206278     1105.0
206279     1105.0
206345     7268.0
206358     1105.0
211488    40000.0
Name: price, Length: 1561, dtype: float64

# Join Operations: pd.merge()

In [ ]:
df_left_joined1 = pd.merge(df, df, left_on = 'airline', right_on = 'airline', how = 'left')
df_left_joined1

# if on condition has the same column name, then only one "on" column

,airline,flight_x,source_city_x,departure_time_x,stops_x,arrival_time_x,destination_city_x,class_x,duration_x,days_left_x,...,flight_y,source_city_y,departure_time_y,stops_y,arrival_time_y,destination_city_y,class_y,duration_y,days_left_y,price_y
0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,...,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953.0
1,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,...,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953.0
2,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,...,SG-8169,Delhi,Evening,zero,Night,Mumbai,Economy,2.33,1,10260.0
3,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,...,SG-2976,Delhi,Evening,one,Night,Mumbai,Economy,4.50,1,12123.0
4,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,...,SG-339,Delhi,Evening,one,Afternoon,Mumbai,Economy,19.58,1,12230.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
650670,Air_India,AI-433,Delhi,Afternoon,one,Afternoon,Mumbai,Business,27.50,45,...,AI-545,Chennai,Evening,one,Morning,Delhi,Economy,13.75,45,3538.0
650671,Air_India,AI-433,Delhi,Afternoon,one,Afternoon,Mumbai,Business,27.50,45,...,AI-551,Chennai,Morning,one,Afternoon,Delhi,Economy,29.00,45,13880.0
650672,Air_India,AI-433,Delhi,Afternoon,one,Afternoon,Mumbai,Business,27.50,45,...,AI-563,Chennai,Afternoon,one,Night,Delhi,Economy,9.58,47,5867.0
650673,Air_India,AI-433,Delhi,Afternoon,one,Afternoon,Mumbai,Business,27.50,45,...,AI-509,Chennai,Early_Morning,one,Night,Mumbai,Economy,14.42,45,5571.0
650674,Air_India,AI-433,Delhi,Afternoon,one,Afternoon,Mumbai,Business,27.50,45,...,AI-433,Delhi,Afternoon,one,Afternoon,Mumbai,Business,27.50,45,40000.0

In [257]:
df_left_joined2 = df.merge(df, left_on = 'airline', right_on = 'airline', how = 'left')
df_left_joined2

# if on condition has the same column name, then only one "on" column

,airline,flight_x,source_city_x,departure_time_x,stops_x,arrival_time_x,destination_city_x,class_x,duration_x,days_left_x,...,flight_y,source_city_y,departure_time_y,stops_y,arrival_time_y,destination_city_y,class_y,duration_y,days_left_y,price_y
0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,...,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953.0
1,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,...,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953.0
2,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,...,SG-8169,Delhi,Evening,zero,Night,Mumbai,Economy,2.33,1,10260.0
3,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,...,SG-2976,Delhi,Evening,one,Night,Mumbai,Economy,4.50,1,12123.0
4,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,...,SG-339,Delhi,Evening,one,Afternoon,Mumbai,Economy,19.58,1,12230.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
650670,Air_India,AI-433,Delhi,Afternoon,one,Afternoon,Mumbai,Business,27.50,45,...,AI-545,Chennai,Evening,one,Morning,Delhi,Economy,13.75,45,3538.0
650671,Air_India,AI-433,Delhi,Afternoon,one,Afternoon,Mumbai,Business,27.50,45,...,AI-551,Chennai,Morning,one,Afternoon,Delhi,Economy,29.00,45,13880.0
650672,Air_India,AI-433,Delhi,Afternoon,one,Afternoon,Mumbai,Business,27.50,45,...,AI-563,Chennai,Afternoon,one,Night,Delhi,Economy,9.58,47,5867.0
650673,Air_India,AI-433,Delhi,Afternoon,one,Afternoon,Mumbai,Business,27.50,45,...,AI-509,Chennai,Early_Morning,one,Night,Mumbai,Economy,14.42,45,5571.0
650674,Air_India,AI-433,Delhi,Afternoon,one,Afternoon,Mumbai,Business,27.50,45,...,AI-433,Delhi,Afternoon,one,Afternoon,Mumbai,Business,27.50,45,40000.0

In [258]:
df_left_joined3 = df.merge(df, on = 'airline', how = 'left')
df_left_joined3

,airline,flight_x,source_city_x,departure_time_x,stops_x,arrival_time_x,destination_city_x,class_x,duration_x,days_left_x,...,flight_y,source_city_y,departure_time_y,stops_y,arrival_time_y,destination_city_y,class_y,duration_y,days_left_y,price_y
0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,...,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953.0
1,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,...,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953.0
2,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,...,SG-8169,Delhi,Evening,zero,Night,Mumbai,Economy,2.33,1,10260.0
3,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,...,SG-2976,Delhi,Evening,one,Night,Mumbai,Economy,4.50,1,12123.0
4,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,...,SG-339,Delhi,Evening,one,Afternoon,Mumbai,Economy,19.58,1,12230.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
650670,Air_India,AI-433,Delhi,Afternoon,one,Afternoon,Mumbai,Business,27.50,45,...,AI-545,Chennai,Evening,one,Morning,Delhi,Economy,13.75,45,3538.0
650671,Air_India,AI-433,Delhi,Afternoon,one,Afternoon,Mumbai,Business,27.50,45,...,AI-551,Chennai,Morning,one,Afternoon,Delhi,Economy,29.00,45,13880.0
650672,Air_India,AI-433,Delhi,Afternoon,one,Afternoon,Mumbai,Business,27.50,45,...,AI-563,Chennai,Afternoon,one,Night,Delhi,Economy,9.58,47,5867.0
650673,Air_India,AI-433,Delhi,Afternoon,one,Afternoon,Mumbai,Business,27.50,45,...,AI-509,Chennai,Early_Morning,one,Night,Mumbai,Economy,14.42,45,5571.0
650674,Air_India,AI-433,Delhi,Afternoon,one,Afternoon,Mumbai,Business,27.50,45,...,AI-433,Delhi,Afternoon,one,Afternoon,Mumbai,Business,27.50,45,40000.0

In [260]:
# other join methods - right
df_right_joined1 = df.merge(df, on = 'airline', how = 'right')
df_right_joined1

,airline,flight_x,source_city_x,departure_time_x,stops_x,arrival_time_x,destination_city_x,class_x,duration_x,days_left_x,...,flight_y,source_city_y,departure_time_y,stops_y,arrival_time_y,destination_city_y,class_y,duration_y,days_left_y,price_y
0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,...,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953.0
1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,...,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953.0
2,SpiceJet,SG-8169,Delhi,Evening,zero,Night,Mumbai,Economy,2.33,1,...,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953.0
3,SpiceJet,SG-2976,Delhi,Evening,one,Night,Mumbai,Economy,4.50,1,...,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953.0
4,SpiceJet,SG-339,Delhi,Evening,one,Afternoon,Mumbai,Economy,19.58,1,...,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
650670,Air_India,AI-545,Chennai,Evening,one,Morning,Delhi,Economy,13.75,45,...,AI-433,Delhi,Afternoon,one,Afternoon,Mumbai,Business,27.50,45,40000.0
650671,Air_India,AI-551,Chennai,Morning,one,Afternoon,Delhi,Economy,29.00,45,...,AI-433,Delhi,Afternoon,one,Afternoon,Mumbai,Business,27.50,45,40000.0
650672,Air_India,AI-563,Chennai,Afternoon,one,Night,Delhi,Economy,9.58,47,...,AI-433,Delhi,Afternoon,one,Afternoon,Mumbai,Business,27.50,45,40000.0
650673,Air_India,AI-509,Chennai,Early_Morning,one,Night,Mumbai,Economy,14.42,45,...,AI-433,Delhi,Afternoon,one,Afternoon,Mumbai,Business,27.50,45,40000.0
650674,Air_India,AI-433,Delhi,Afternoon,one,Afternoon,Mumbai,Business,27.50,45,...,AI-433,Delhi,Afternoon,one,Afternoon,Mumbai,Business,27.50,45,40000.0

In [261]:
# other join methods - inner
df_inner_joined1 = df.merge(df, on = 'airline', how = 'inner')
df_inner_joined1

,airline,flight_x,source_city_x,departure_time_x,stops_x,arrival_time_x,destination_city_x,class_x,duration_x,days_left_x,...,flight_y,source_city_y,departure_time_y,stops_y,arrival_time_y,destination_city_y,class_y,duration_y,days_left_y,price_y
0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,...,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953.0
1,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,...,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953.0
2,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,...,SG-8169,Delhi,Evening,zero,Night,Mumbai,Economy,2.33,1,10260.0
3,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,...,SG-2976,Delhi,Evening,one,Night,Mumbai,Economy,4.50,1,12123.0
4,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,...,SG-339,Delhi,Evening,one,Afternoon,Mumbai,Economy,19.58,1,12230.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
650670,Air_India,AI-433,Delhi,Afternoon,one,Afternoon,Mumbai,Business,27.50,45,...,AI-545,Chennai,Evening,one,Morning,Delhi,Economy,13.75,45,3538.0
650671,Air_India,AI-433,Delhi,Afternoon,one,Afternoon,Mumbai,Business,27.50,45,...,AI-551,Chennai,Morning,one,Afternoon,Delhi,Economy,29.00,45,13880.0
650672,Air_India,AI-433,Delhi,Afternoon,one,Afternoon,Mumbai,Business,27.50,45,...,AI-563,Chennai,Afternoon,one,Night,Delhi,Economy,9.58,47,5867.0
650673,Air_India,AI-433,Delhi,Afternoon,one,Afternoon,Mumbai,Business,27.50,45,...,AI-509,Chennai,Early_Morning,one,Night,Mumbai,Economy,14.42,45,5571.0
650674,Air_India,AI-433,Delhi,Afternoon,one,Afternoon,Mumbai,Business,27.50,45,...,AI-433,Delhi,Afternoon,one,Afternoon,Mumbai,Business,27.50,45,40000.0

In [263]:
# other join methods - outer
df_inner_joined1 = df.merge(df, on = 'airline', how = 'outer')
df_inner_joined1

,airline,flight_x,source_city_x,departure_time_x,stops_x,arrival_time_x,destination_city_x,class_x,duration_x,days_left_x,...,flight_y,source_city_y,departure_time_y,stops_y,arrival_time_y,destination_city_y,class_y,duration_y,days_left_y,price_y
0,Air Asia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,...,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956.0
1,Air Asia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,...,I5-747,Delhi,Evening,one,Early_Morning,Mumbai,Economy,12.25,1,5949.0
2,Air Asia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,...,I5-744,Delhi,Morning,one,Afternoon,Mumbai,Economy,5.83,1,8869.0
3,Air Asia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,...,I5-784,Delhi,Evening,one,Early_Morning,Mumbai,Economy,15.17,1,12539.0
4,Air Asia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,...,I5-721,Delhi,Night,one,Early_Morning,Mumbai,Economy,10.50,5,5949.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
650670,Vistara,UK-828,Chennai,Early_Morning,one,Afternoon,Delhi,Economy,5.67,5,...,UK-834,Chennai,Evening,zero,Evening,Delhi,Economy,2.75,3,13233.0
650671,Vistara,UK-828,Chennai,Early_Morning,one,Afternoon,Delhi,Economy,5.67,5,...,UK-822,Chennai,Morning,one,Evening,Delhi,Economy,10.00,3,14283.0
650672,Vistara,UK-828,Chennai,Early_Morning,one,Afternoon,Delhi,Economy,5.67,5,...,UK-824,Chennai,Night,one,Morning,Delhi,Economy,11.58,4,13023.0
650673,Vistara,UK-828,Chennai,Early_Morning,one,Afternoon,Delhi,Economy,5.67,5,...,UK-826,Chennai,Afternoon,one,Evening,Delhi,Economy,5.58,5,11448.0
650674,Vistara,UK-828,Chennai,Early_Morning,one,Afternoon,Delhi,Economy,5.67,5,...,UK-828,Chennai,Early_Morning,one,Afternoon,Delhi,Economy,5.67,5,11868.0

In [ ]:
# other join methods - cross
cross_df = pd.DataFrame({"test": [1,2]})
df_inner_joined1 = df.merge(cross_df, how = 'cross')
df_inner_joined1

# cross join does not have on condition, it will produce Cartesian product

,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,test
0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953.0,1
1,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953.0,2
2,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953.0,1
3,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953.0,2
4,Air Asia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
3117,Indigo,6E-7127,Chennai,Afternoon,one,Night,Hyderabad,Economy,9.50,45,7268.0,2
3118,Indigo,6E-7259,Chennai,Afternoon,one,Night,Hyderabad,Economy,5.92,46,1105.0,1
3119,Indigo,6E-7259,Chennai,Afternoon,one,Night,Hyderabad,Economy,5.92,46,1105.0,2
3120,Air_India,AI-433,Delhi,Afternoon,one,Afternoon,Mumbai,Business,27.50,45,40000.0,1
3121,Air_India,AI-433,Delhi,Afternoon,one,Afternoon,Mumbai,Business,27.50,45,40000.0,2

# Set Operations: pd.concat()

In [309]:
df = pd.DataFrame({
    'Students': ['A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C'],
    'Courses': ['Chinese', 'Chinese', 'Chinese', 'Mathematics', 'Mathematics', 'Mathematics', 'English', 'English', 'English'],
    'Scores': [96,85,94,80,97,90,100,99, 98]
    
})

## Pivot

In [310]:
# long table to wide table
df.pivot(index = 'Students',columns = 'Courses', values = 'Scores')

Courses   Chinese  English  Mathematics
Students
A              96      100           80
B              85       99           97
C              94       98           90

In [311]:
# pivot table with aggregation
df.pivot_table(index = 'Students', values = 'Scores', aggfunc = 'sum')
# if having multiple dimension, can do as follows
# df.pivot_table(index = 'col1', columns = 'col2', values = 'col3', aggfunc = 'method')

          Scores
Students
A            276
B            281
C            282

## Melt by pd.melt()

In [312]:
df = df.pivot(index = 'Students',columns = 'Courses', values = 'Scores')
df

Courses   Chinese  English  Mathematics
Students
A              96      100           80
B              85       99           97
C              94       98           90

In [313]:
df = df.reset_index()
df # Course is the name for column names

Courses Students  Chinese  English  Mathematics
0              A       96      100           80
1              B       85       99           97
2              C       94       98           90

In [314]:
df = pd.melt(df, id_vars = ['Students'], var_name = 'Courses', value_name = 'Scores')
df

  Students      Courses  Scores
0        A      Chinese      96
1        B      Chinese      85
2        C      Chinese      94
3        A      English     100
4        B      English      99
5        C      English      98
6        A  Mathematics      80
7        B  Mathematics      97
8        C  Mathematics      90

In [315]:
df = df.stack()
df

0  Students              A
   Courses         Chinese
   Scores               96
1  Students              B
   Courses         Chinese
   Scores               85
2  Students              C
   Courses         Chinese
   Scores               94
3  Students              A
   Courses         English
   Scores              100
4  Students              B
   Courses         English
   Scores               99
5  Students              C
   Courses         English
   Scores               98
6  Students              A
   Courses     Mathematics
   Scores               80
7  Students              B
   Courses     Mathematics
   Scores               97
8  Students              C
   Courses     Mathematics
   Scores               90
dtype: object

In [316]:
df = df.unstack()
df

  Students      Courses Scores
0        A      Chinese     96
1        B      Chinese     85
2        C      Chinese     94
3        A      English    100
4        B      English     99
5        C      English     98
6        A  Mathematics     80
7        B  Mathematics     97
8        C  Mathematics     90

# Group By

Common Aggregation Functions  
1. max()/min()
2. mean()/median()
3. sum()
4. count()/size() -> count() ignores NULL, while size() does not.
5. std()/var()
6. nunique() # count the number of unique values

In [319]:
new_series = df.groupby('Students')['Scores'].sum()
new_series

Students
A    276
B    281
C    282
Name: Scores, dtype: object

In [320]:
new_df = df.groupby('Students', as_index = False)['Scores'].sum()
new_df

  Students Scores
0        A    276
1        B    281
2        C    282

In [ ]:
## multiple 
new_df2 = df.groupby('Students', as_index = False)['Scores'].agg(['mean', 'sum','max', 'min'])
new_df2

  Students       mean  sum  max min
0        A       92.0  276  100  80
1        B  93.666667  281   99  85
2        C       94.0  282   98  90

In [324]:
## multiple 
new_df3 = df.groupby('Students', as_index = False).agg({'Courses':'count', 'Scores':'sum'})
new_df3

  Students  Courses Scores
0        A        3    276
1        B        3    281
2        C        3    282

In [ ]:
## keep original rows -> transforms!!!
df['sum_of_scores'] = df.groupby('Students', as_index = False)['Scores'].transform('sum')
df

  Students      Courses Scores sum_of_scores
0        A      Chinese     96           276
1        B      Chinese     85           281
2        C      Chinese     94           282
3        A      English    100           276
4        B      English     99           281
5        C      English     98           282
6        A  Mathematics     80           276
7        B  Mathematics     97           281
8        C  Mathematics     90           282

**Ranking**  
Use with groupby.  
rank(method = 'method', ascending = True/False)  
method can be:  
1. average: 重复则取平均名次
2. min: 同一组重复值取最小的名次，相当于RANK
3. max: 同一组重复值取最大的名次
4. first: 同一组重复值按出现顺序分配名词，相当于row_number
5. dense: 同一组重复值取最小的名词，且不留空缺，相当于dense_rank

In [328]:
### Ranking
df['rank'] = df.groupby('Students')['Scores'].rank(method = 'min', ascending = False)
df

  Students      Courses Scores sum_of_scores  rank
0        A      Chinese     96           276   2.0
1        B      Chinese     85           281   3.0
2        C      Chinese     94           282   2.0
3        A      English    100           276   1.0
4        B      English     99           281   1.0
5        C      English     98           282   1.0
6        A  Mathematics     80           276   3.0
7        B  Mathematics     97           281   2.0
8        C  Mathematics     90           282   3.0

In [346]:
## rolling window -> if sorting needed, should sort at first
df['rolling_mean'] = df.groupby('Students')['Scores'].transform(lambda x: x.rolling(
    window = 3, min_periods = 3).mean()
    )
df

  Students      Courses Scores sum_of_scores  rank  rolling_mean  cum_sum
0        A      Chinese     96           276   2.0           NaN     96.0
1        B      Chinese     85           281   3.0           NaN     85.0
2        C      Chinese     94           282   2.0           NaN     94.0
3        A      English    100           276   1.0           NaN    196.0
4        B      English     99           281   1.0           NaN    184.0
5        C      English     98           282   1.0           NaN    192.0
6        A  Mathematics     80           276   3.0     92.000000    276.0
7        B  Mathematics     97           281   2.0     93.666667    281.0
8        C  Mathematics     90           282   3.0     94.000000    282.0

In [341]:
## cumulative sum
df['cum_sum'] = df.groupby('Students', as_index = False)['Scores'].transform(lambda x: x.expanding().sum())
df

  Students      Courses Scores sum_of_scores  rank  rolling_mean  cum_sum
0        A      Chinese     96           276   2.0           NaN     96.0
1        B      Chinese     85           281   3.0           NaN     85.0
2        C      Chinese     94           282   2.0     91.666667     94.0
3        A      English    100           276   1.0     93.000000    196.0
4        B      English     99           281   1.0     97.666667    184.0
5        C      English     98           282   1.0     99.000000    192.0
6        A  Mathematics     80           276   3.0     92.333333    276.0
7        B  Mathematics     97           281   2.0     91.666667    281.0
8        C  Mathematics     90           282   3.0     89.000000    282.0

In [349]:
### shift
df['shifted_scores'] = df['Scores'].shift(1) # shift down
df['shifted2_scores'] = df['Scores'].shift(-1) # shift up
df

,Students,Courses,Scores,sum_of_scores,rank,rolling_mean,cum_sum,shifted_scores,shifted2_scores
0,A,Chinese,96,276,2.0,NaN,96.0,None,85
1,B,Chinese,85,281,3.0,NaN,85.0,96,94
2,C,Chinese,94,282,2.0,NaN,94.0,85,100
3,A,English,100,276,1.0,NaN,196.0,94,99
4,B,English,99,281,1.0,NaN,184.0,100,98
5,C,English,98,282,1.0,NaN,192.0,99,80
6,A,Mathematics,80,276,3.0,92.000000,276.0,98,97
7,B,Mathematics,97,281,2.0,93.666667,281.0,80,90
8,C,Mathematics,90,282,3.0,94.000000,282.0,97,None

In [ ]:
## shift with group by
df['shifted3_scores'] = df.groupby('Students')['Scores'].transform(lambda x: x.shift(1))
df

,Students,Courses,Scores,sum_of_scores,rank,rolling_mean,cum_sum,shifted_scores,shifted2_scores,shifted3_scores
0,A,Chinese,96,276,2.0,NaN,96.0,None,85,None
1,B,Chinese,85,281,3.0,NaN,85.0,96,94,None
2,C,Chinese,94,282,2.0,NaN,94.0,85,100,None
3,A,English,100,276,1.0,NaN,196.0,94,99,96
4,B,English,99,281,1.0,NaN,184.0,100,98,85
5,C,English,98,282,1.0,NaN,192.0,99,80,94
6,A,Mathematics,80,276,3.0,92.000000,276.0,98,97,100
7,B,Mathematics,97,281,2.0,93.666667,281.0,80,90,99
8,C,Mathematics,90,282,3.0,94.000000,282.0,97,None,98

# Date

In [423]:
df = pd.DataFrame(
    {"date":['2025-01-01', '2025-02-01', '2025-03-01', '2025-04-01', '2025-05-01','2025-06-01', '2025-07-01', '2025-08-01', '2025-09-01', '2025-10-01'],
    "exam":['Chinese', 'English', 'Mathematics','Biology', 'Chemistry', 'Physics', 'History','Society', 'Geography', 'Economics'],
    'scores':[98,99, 100, 100,100,99, 98, 97,96,95]
    }
)

In [424]:
df

         date         exam  scores
0  2025-01-01      Chinese      98
1  2025-02-01      English      99
2  2025-03-01  Mathematics     100
3  2025-04-01      Biology     100
4  2025-05-01    Chemistry     100
5  2025-06-01      Physics      99
6  2025-07-01      History      98
7  2025-08-01      Society      97
8  2025-09-01    Geography      96
9  2025-10-01    Economics      95

In [425]:
# string to date
df['date'] = pd.to_datetime(df['date'],
errors = 'coerce', # cannot parse then NaN
format = '%Y-%m-%d',
utc = True)

In [426]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    10 non-null     datetime64[ns, UTC]
 1   exam    10 non-null     object
 2   scores  10 non-null     int64
dtypes: datetime64[ns, UTC](1), int64(1), object(1)
memory usage: 372.0+ bytes

In [427]:
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df['day'] = df['date'].dt.day
df['dayofweek'] = df['date'].dt.weekday
df['dayofyear'] = df['date'].dt.dayofyear
df

,date,exam,scores,year,month,day,dayofweek,dayofyear
0,2025-01-01 00:00:00+00:00,Chinese,98,2025,1,1,2,1
1,2025-02-01 00:00:00+00:00,English,99,2025,2,1,5,32
2,2025-03-01 00:00:00+00:00,Mathematics,100,2025,3,1,5,60
3,2025-04-01 00:00:00+00:00,Biology,100,2025,4,1,1,91
4,2025-05-01 00:00:00+00:00,Chemistry,100,2025,5,1,3,121
5,2025-06-01 00:00:00+00:00,Physics,99,2025,6,1,6,152
6,2025-07-01 00:00:00+00:00,History,98,2025,7,1,1,182
7,2025-08-01 00:00:00+00:00,Society,97,2025,8,1,4,213
8,2025-09-01 00:00:00+00:00,Geography,96,2025,9,1,0,244
9,2025-10-01 00:00:00+00:00,Economics,95,2025,10,1,2,274

# String Operation

## Non-regularisation

In [428]:
df[df['exam'].str.startswith('P')]

,date,exam,scores,year,month,day,dayofweek,dayofyear
5,2025-06-01 00:00:00+00:00,Physics,99,2025,6,1,6,152

In [429]:
df[df['exam'].str.endswith('cs')]

,date,exam,scores,year,month,day,dayofweek,dayofyear
2,2025-03-01 00:00:00+00:00,Mathematics,100,2025,3,1,5,60
5,2025-06-01 00:00:00+00:00,Physics,99,2025,6,1,6,152
9,2025-10-01 00:00:00+00:00,Economics,95,2025,10,1,2,274

In [430]:
df['exam'] = df['exam'].str.lower() # 全部小写
df['exam']

0        chinese
1        english
2    mathematics
3        biology
4      chemistry
5        physics
6        history
7        society
8      geography
9      economics
Name: exam, dtype: object

In [431]:
df['exam'] = df['exam'].str.upper() # 全部大写
df['exam']

0        CHINESE
1        ENGLISH
2    MATHEMATICS
3        BIOLOGY
4      CHEMISTRY
5        PHYSICS
6        HISTORY
7        SOCIETY
8      GEOGRAPHY
9      ECONOMICS
Name: exam, dtype: object

In [432]:
df['exam'] = df['exam'].str.capitalize() # 整个字符串第一个字母大写，其他小写
df['exam']

0        Chinese
1        English
2    Mathematics
3        Biology
4      Chemistry
5        Physics
6        History
7        Society
8      Geography
9      Economics
Name: exam, dtype: object

In [433]:
df['exam'] = df['exam'].str.title() # 每个单词首字母大写，其他小写
df['exam']

0        Chinese
1        English
2    Mathematics
3        Biology
4      Chemistry
5        Physics
6        History
7        Society
8      Geography
9      Economics
Name: exam, dtype: object

In [434]:
df['exam'] = df['exam'].str.strip()
df['exam']

0        Chinese
1        English
2    Mathematics
3        Biology
4      Chemistry
5        Physics
6        History
7        Society
8      Geography
9      Economics
Name: exam, dtype: object

In [435]:
df['exam'] = df['exam'].str.lstrip()
df['exam']

0        Chinese
1        English
2    Mathematics
3        Biology
4      Chemistry
5        Physics
6        History
7        Society
8      Geography
9      Economics
Name: exam, dtype: object

In [436]:
df['exam'] = df['exam'].str.rstrip()
df['exam']

0        Chinese
1        English
2    Mathematics
3        Biology
4      Chemistry
5        Physics
6        History
7        Society
8      Geography
9      Economics
Name: exam, dtype: object

In [437]:
df = df[df['exam'].str.contains('cs')]
df

,date,exam,scores,year,month,day,dayofweek,dayofyear
2,2025-03-01 00:00:00+00:00,Mathematics,100,2025,3,1,5,60
5,2025-06-01 00:00:00+00:00,Physics,99,2025,6,1,6,152
9,2025-10-01 00:00:00+00:00,Economics,95,2025,10,1,2,274

In [438]:
df = df[df['exam'].str.contains(r'M')]
df

,date,exam,scores,year,month,day,dayofweek,dayofyear
2,2025-03-01 00:00:00+00:00,Mathematics,100,2025,3,1,5,60

In [439]:
df

,date,exam,scores,year,month,day,dayofweek,dayofyear
2,2025-03-01 00:00:00+00:00,Mathematics,100,2025,3,1,5,60

In [440]:
df['exam'] = df['exam'].str.replace(r'e', 'm')
df

C:\Users\junqi.wu\AppData\Local\Temp\ipykernel_4580\1385275655.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['exam'] = df['exam'].str.replace(r'e', 'm')

,date,exam,scores,year,month,day,dayofweek,dayofyear
2,2025-03-01 00:00:00+00:00,Mathmmatics,100,2025,3,1,5,60

In [442]:
df['extraction'] = df['exam'].str.extract(r"([Mm]{2,})")
df

C:\Users\junqi.wu\AppData\Local\Temp\ipykernel_4580\3044818839.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['extraction'] = df['exam'].str.extract(r"([Mm]{2,})")

,date,exam,scores,year,month,day,dayofweek,dayofyear,extraction
2,2025-03-01 00:00:00+00:00,Mathmmatics,100,2025,3,1,5,60,mm

In [443]:
df['exam'].str.split('m', expand = True)

      0 1      2
2  Math    atics

In [444]:
df['exam'].str.len()

2    11
Name: exam, dtype: int64

In [448]:
# slicing
print(df['exam'].str[0:3])
print(df['exam'].str.slice(0,3))

2    Mat
Name: exam, dtype: object
2    Mat
Name: exam, dtype: object

# Sorting

In [449]:
df = pd.DataFrame(
    {"date":['2025-01-01', '2025-02-01', '2025-03-01', '2025-04-01', '2025-05-01','2025-06-01', '2025-07-01', '2025-08-01', '2025-09-01', '2025-10-01'],
    "exam":['Chinese', 'English', 'Mathematics','Biology', 'Chemistry', 'Physics', 'History','Society', 'Geography', 'Economics'],
    'scores':[98,99, 100, 100,100,99, 98, 97,96,95]
    }
)

## Sort by values

In [450]:
df = df.sort_values(by ='scores',ascending = True)
df

         date         exam  scores
9  2025-10-01    Economics      95
8  2025-09-01    Geography      96
7  2025-08-01      Society      97
0  2025-01-01      Chinese      98
6  2025-07-01      History      98
1  2025-02-01      English      99
5  2025-06-01      Physics      99
2  2025-03-01  Mathematics     100
4  2025-05-01    Chemistry     100
3  2025-04-01      Biology     100

In [451]:
df = df.sort_values(by = ['scores', 'exam'],ascending =[False,  True])
df

         date         exam  scores
3  2025-04-01      Biology     100
4  2025-05-01    Chemistry     100
2  2025-03-01  Mathematics     100
1  2025-02-01      English      99
5  2025-06-01      Physics      99
0  2025-01-01      Chinese      98
6  2025-07-01      History      98
7  2025-08-01      Society      97
8  2025-09-01    Geography      96
9  2025-10-01    Economics      95

## Sort by index

In [452]:
df = df.sort_index() # default is ascending
df

         date         exam  scores
0  2025-01-01      Chinese      98
1  2025-02-01      English      99
2  2025-03-01  Mathematics     100
3  2025-04-01      Biology     100
4  2025-05-01    Chemistry     100
5  2025-06-01      Physics      99
6  2025-07-01      History      98
7  2025-08-01      Society      97
8  2025-09-01    Geography      96
9  2025-10-01    Economics      95

In [453]:
df = df.sort_index(ascending = False)
df

         date         exam  scores
9  2025-10-01    Economics      95
8  2025-09-01    Geography      96
7  2025-08-01      Society      97
6  2025-07-01      History      98
5  2025-06-01      Physics      99
4  2025-05-01    Chemistry     100
3  2025-04-01      Biology     100
2  2025-03-01  Mathematics     100
1  2025-02-01      English      99
0  2025-01-01      Chinese      98

In [454]:
df = df.sort_index(axis =1) # sorting by column names
df

         date         exam  scores
9  2025-10-01    Economics      95
8  2025-09-01    Geography      96
7  2025-08-01      Society      97
6  2025-07-01      History      98
5  2025-06-01      Physics      99
4  2025-05-01    Chemistry     100
3  2025-04-01      Biology     100
2  2025-03-01  Mathematics     100
1  2025-02-01      English      99
0  2025-01-01      Chinese      98